baseURL: "https://skavi.fr"
languageCode: "fr-fr"
title: "Skavi"
theme: "netlify-basic"
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true
assets:
  favicon: "/skvfavicon.ico"
